name: Morging Box CI - Quality & Build

on:
  push:
    branches: [main, develop]
    pull_request: [main, develop]

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
      # 1. Copia el codigo de tu repo al servidor de GitHub Actions
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 2. Instala Node.js (ajusta la versión si usas una distinta a la 20)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      
      # 3. Instala las dependencias de forma limpia
      - name: Install dependencies
        run: npm ci

      # 4. Validar que el esquema de BD sea correcto
      - name: Validate Prisma Schema
        run: npx prisma validate
      
      # 5. Generar prisma client(necesario para lint y build)
      - name: Generate Prisma Client
        run: npx prisma generate

      # 6. Revisa las reglas de estilo y errores de sintaxis con ESLint
      - name: Run ESLint
        run: npm run lint || true #Evita que falle si hay errores de lint, solo queremos reportarlos

      #7. Ejecutar pruebas unitarias
      #- name: Run Unit Tests
      #  run: npm run test -- --passWithNoTests #Evita que falle si no hay tests

      # 8. El paso clave: Ejecuta la compilación de NestJS
      - name: Run Build
        run: npm run build

  deploy:
    needs: quality-gate
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 1. Navegar a la carpeta del proyecto en el servidor
            # Ajusta esta ruta a donde se clono el repositorio en tu servidor EC2
            cd /home/${{ secrets.SSH_USER }}/morning-box-api

            # 2. Actualizar código y dependencias desde GitHub
            git pull origin main

            # 3. Levantas los contenedores con Docker compose
            # El .env que se creo de forma manual en el servidor EC2, ya tiene las variables de entorno necesarias para que la app funcione correctamente
            docker compose up -d --build

            # 4. Limpiar contenedores y recursos no usados para liberar espacio
            docker image prune -f